### PR TITLE
Update icons

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

**Comment by msevestre** [comment]
@Yuri05 The idea is to only use icons from the ospsuite (*.ico) if possible. We have set the size to 32 everywhere to have a consistent display

**Comment by msevestre** [comment]
@Yuri05 If you are ok with these changes, please merge
Next, we will move all screenshots that are under icons in under the image folders (so that we do not mix and match)

Then we found a bunch of inconsistencies that we need to discuss
anything else?

**Comment by Yuri05** [comment]
@msevestre In the changed markdown some new icons are not shown due to case sensitivity(?)
E.g. because icons are referenced as ".../human.ico" instead of ".../Human.ico" it looks like this:
grafik
If later for the rendered website it does not matter - we can merge

**Comment by msevestre** [comment]
no way for me to know if this will be ok or not. vscode has no problem with it
Are you sure this is due to casing?

**Comment by msevestre** [comment]
ok let's make sure we use the right casing.

**Comment by Yuri05** [comment]
>Are you sure this is due to casing?

Yes. E.g. enter in Firefox
https://github.com/Open-Systems-Pharmacology/docs/blob/update-icons/assets/icons/human.ico
vs.
https://github.com/Open-Systems-Pharmacology/docs/blob/update-icons/assets/icons/Human.ico

Which actually really surprises me

**Pull request merged**
