### PR TITLE
Fixes formatting in Create individual

### PR DESCRIPTION
**Pull request by Yuri05**
Just another case where formatting looks good in MD but Gitbook destroys it.
Tried to change it - let's see if it's better now after rendering.

### CODE REVIEW

**Comment by Yuri05** [comment]
Still corrupted after rendering.. ok, let's wait for Gitbook answer

**Comment by msevestre** [comment]
Not sure what issue you are talking about? Looks fine to me

**Comment by msevestre** [comment]
image

**Comment by Yuri05** [comment]
That's how it looks like in MD and how it should be (s. scaling method options)

grafik

**Pull request merged**
